<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/10_Arr_Or_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy kutubxonasini chaqirib olamiz

In [ ]:
import numpy as np

## Massivga yo'naltirilgan dasturlash

# Arifmetik amallar

## Ko'paytirish, bo'lish, qo'shish, ayirish, va h.k amallar

In [ ]:
# data
arr1 = np.arange(6).reshape(2, 3) # 0~6 gacha bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6dan 11 gacha bo'lgan elementlardan tashkil topgan arrey

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# Ko'paytirish
arr1 * arr2 # arr1 ning mos elementlarini arr2 ning mos elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
# Bo'lish
arr2/arr1  # arr1 ning mos elementlarini arr2 ning mos elementlariga bo'lib beradi. Hamda 0 bo'lib bo'lmagani uchun inf bilan xato berayabdi

/tmp/ipython-input-2983155892.py:2: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1  # arr1 ning mos elementlarini arr2 ning mos elementlariga bo'lib beradi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [ ]:
# Qo'shish
arr1 + arr2 # arr1 ning mos elementlarini arr2 ning mos elementlariga qo'shib beradi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# Ayirish
arr2-arr1 # arr2 ning mos elementlarini arr1 ning mos elementlaridan ayirib beradi

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
# kvadratga oshirish (sqare)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
# kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])