<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/11_Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Sciense va Sun'iy Intellekt Praktikum**

## **Ma'lumotlar tahlili**

## **2.1.NumPy kutubxonasi bilan ishlash**

## NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

## 2.1.3.Massivga yo'naltirilgan dasturlash

## Matematik va Statistik usullarni qo'llash

In [ ]:
# data
arr = np.random.randn(5, 4) # (5, 4) o'lchamli massiv (random)
arr

array([[ 0.05178991, -0.55750664,  0.32358862, -0.981566  ],
       [ 0.77441271,  0.88725554, -0.12015337, -0.20044701],
       [-0.38950731,  0.44162435, -0.47132927,  0.89267547],
       [-1.60887138, -0.83711989, -0.37646403, -0.28869997],
       [ 0.66763593,  1.80907664, -0.42443172, -0.59755504]])

## sum metodi

In [ ]:
arr.sum()

np.float64(-1.0055924782006884)

In [ ]:
print(arr.sum()) # arr ning barcha elementlarini yig;indisini hisoblab beradi

-1.0055924782006884


In [ ]:
np.sum(arr) # Bu ham shu hisobni bajaradi

np.float64(-1.0055924782006884)

In [ ]:
# Bunda pastda ustun va qatorga hisoblash amalga oshirilga index bilan. Index gorizantalga 1 dan, vertikalga 0 dan boshlanadi.

In [ ]:
arr.sum(axis=1) # gorizantal qilib yig'indini hisoblaydi

array([-1.16369412,  1.34106787,  0.47346323, -3.11115527,  1.45472581])

In [ ]:
arr.sum(axis=0) # ustun yani vertikal qilib yig'indini hisoblaydi

array([-0.50454014,  1.74332999, -1.06878978, -1.17559255])

## mean metodi

In [ ]:
# sodda ma'lumot
data = np.arange(5) # 0 ~ 5 gacha bo'lgan elementlardan tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [ ]:
mean = np.sum(data)/len(data) # Bunda sum bilan hammasini qo'shib, len orqali nechtaligini aniqlab bo'layabmiz
print(mean)

2.0


In [ ]:
# mean metodi orqali o'rtacha qiymat aniqlanadi. sonlar qo'shilib nechta son bo'lsa shunga bo'linadi
# numpy mean
np.mean(data)

np.float64(2.0)

In [ ]:
data.mean() # Bu ham shu vazifani bajaradi

np.float64(2.0)

In [ ]:
arr

array([[ 0.05178991, -0.55750664,  0.32358862, -0.981566  ],
       [ 0.77441271,  0.88725554, -0.12015337, -0.20044701],
       [-0.38950731,  0.44162435, -0.47132927,  0.89267547],
       [-1.60887138, -0.83711989, -0.37646403, -0.28869997],
       [ 0.66763593,  1.80907664, -0.42443172, -0.59755504]])

In [ ]:
np.mean(arr)

np.float64(-0.05027962391003442)

In [ ]:
ortacha = arr.mean()
print(ortacha) # arr ning o'rtacha qiymati

-0.05027962391003442


In [ ]:
np.mean(arr, axis=1) # ustunlar o'rtacha qiymati yani gorizantal bo'yicha

array([-0.29092353,  0.33526697,  0.11836581, -0.77778882,  0.36368145])

In [ ]:
np.mean(arr, axis=0) # qatorlar o'rtacha qiymati yani vertikal bo'yicha

array([-0.10090803,  0.348666  , -0.21375796, -0.23511851])

## cumsum metodi

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
data.cumsum() # ( 0, 0+1, 0+1+2, 0+1+2+3, 0+1+2+3+4 ) yani shunday jarayonda hisoblaydi.

array([ 0,  1,  3,  6, 10])

## std metodi (Standart og'ish)

In [ ]:
data1 = np.arange(1, 5)
data1

array([1, 2, 3, 4])

In [ ]:
np.std(data1) # 'data1' massivining standart og'ishini hisoblaydi

np.float64(1.118033988749895)

In [ ]:
data1.std() # Bu ham shu vazifani bajaradi

np.float64(1.118033988749895)

In [ ]:
np.std(arr) # 'arr' massivining barcha elementlari bo'yicha standart og'ish

np.float64(0.7716365226943616)

In [ ]:
np.std(arr, axis=1) # Gorizontal (qatorlar) bo'yicha standart og'ish

array([0.51066899, 0.4979803 , 0.5722165 , 0.52308887, 0.96522712])

In [ ]:
np.std(arr, axis=0) # Vertikal (ustunlar) bo'yicha standart og'ish

array([0.86456994, 0.96527262, 0.29485686, 0.62682317])

## var metodi (Dispersiya)

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
np.var(data) # 'data' massivining dispersiyasini hisoblaydi

np.float64(2.0)

In [ ]:
data.var() # Bu ham shu vazifani bajaradi

np.float64(2.0)

In [ ]:
np.var(arr) # 'arr' massivining barcha elementlari bo'yicha dispersiya

np.float64(0.5954229231558459)

In [ ]:
np.var(arr, axis=1) # Gorizontal (qatorlar) bo'yicha dispersiya

array([0.26078281, 0.24798438, 0.32743173, 0.27362197, 0.93166338])

In [ ]:
np.var(arr, axis=0) # Vertikal (ustunlar) bo'yicha dispersiya

array([0.74748117, 0.93175124, 0.08694057, 0.39290729])

## min metodi (Minimal qiymat)

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
np.min(data) # 'data' massividagi eng kichik qiymatni topadi

np.int64(0)

In [ ]:
data.min() # Bu ham shu vazifani bajaradi

np.int64(0)

In [ ]:
np.min(arr) # 'arr' massividagi barcha elementlar ichidan eng kichik qiymat

np.float64(-1.60887137722638)

In [ ]:
np.min(arr, axis=1) # Gorizontal (qatorlar) bo'yicha minimal qiymatlar

array([-0.981566  , -0.20044701, -0.47132927, -1.60887138, -0.59755504])

In [ ]:
np.min(arr, axis=0) # Vertikal (ustunlar) bo'yicha minimal qiymatlar

array([-1.60887138, -0.83711989, -0.47132927, -0.981566  ])

## max metodi (Maksimal qiymat)

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
np.max(data) # 'data' massividagi eng katta qiymatni topadi

np.int64(4)

In [ ]:
data.max() # Bu ham shu vazifani bajaradi

np.int64(4)

In [ ]:
np.max(arr) # 'arr' massividagi barcha elementlar ichidan eng katta qiymat

np.float64(1.8090766379366414)

In [ ]:
np.max(arr, axis=1) # Gorizontal (qatorlar) bo'yicha maksimal qiymatlar

array([ 0.32358862,  0.88725554,  0.89267547, -0.28869997,  1.80907664])

In [ ]:
np.max(arr, axis=0) # Vertikal (ustunlar) bo'yicha maksimal qiymatlar

array([0.77441271, 1.80907664, 0.32358862, 0.89267547])

## cumprod metodi (Kumulyativ ko'paytma)

In [ ]:
data1 = np.arange(1, 5)
data1

array([1, 2, 3, 4])

In [ ]:
data1.cumprod() # (...) ya'ni har bir elementgacha bo'lgan ko'paytmani hisoblaydi.

array([ 1,  2,  6, 24])

In [ ]:
arr.cumprod() # 'arr' massivining barcha elementlari bo'yicha kumulyativ ko'paytma

array([ 5.17899086e-02, -2.88732180e-02, -9.34304467e-03,  9.17081498e-03,
        7.10199566e-03,  6.30128497e-03, -7.57120641e-04,  1.51762565e-04,
       -5.91126284e-05, -2.61055758e-05,  1.23043220e-05,  1.09837663e-05,
       -1.76714673e-05,  1.47931367e-05, -5.56908386e-06,  1.60779437e-06,
        1.07342129e-06,  1.94190137e-06, -8.24204541e-07,  4.92507577e-07])

In [ ]:
arr.cumprod(axis=1) # Gorizontal (qatorlar) bo'yicha kumulyativ ko'paytma

array([[ 0.05178991, -0.02887322, -0.00934304,  0.00917081],
       [ 0.77441271,  0.68710196, -0.08255762,  0.01654843],
       [-0.38950731, -0.17201591,  0.08107613,  0.07237467],
       [-1.60887138,  1.34681823, -0.50702862,  0.14637915],
       [ 0.66763593,  1.20780456, -0.51263057,  0.30632498]])

In [ ]:
arr.cumprod(axis=0) # Vertikal (ustunlar) bo'yicha kumulyativ ko'paytma

array([[ 0.05178991, -0.55750664,  0.32358862, -0.981566  ],
       [ 0.04010676, -0.49465085, -0.03888026,  0.19675197],
       [-0.01562188, -0.21844986,  0.01832541,  0.17563565],
       [ 0.02513359,  0.18286872, -0.00689886, -0.05070601],
       [ 0.01678009,  0.33082353,  0.00292809,  0.03029963]])