<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/13_Amaliy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Yangi funksiya**

In [ ]:
def salom_ber():
  """Salom beruvchi funksiya"""
  print('Assalomu alaykum!')

# Misol uchun bajarildi bu funksiya

In [ ]:
salom_ber()

Assalomu alaykum!


## **Yangi funksiya**

In [ ]:
def salom_ber(ism):
  """Foydalanuvchining ismini qabul qilib unga
  Salom beruvchi funksiya"""
  print(f"Assalomu alaykum hurmatli {ism.title()}!")

# ism_yani_biz_kiritgan_ismga_salom_beradi_bu_parametr_deyiladi

In [ ]:
salom_ber('Ali')
salom_ber('Vali')

Assalomu alaykum hurmatli Ali!
Assalomu alaykum hurmatli Vali!


In [ ]:
salom_ber(salom_ber.__doc__)
# bundan qanday foydalanish haqidagi malumotni chiqaradi

Assalomu alaykum hurmatli Foydalanuvchining Ismini Qabul Qilib Unga 
  Salom Beruvchi Funksiya!


## **Yangi funksiya**

In [ ]:
def ism_familiya(ism, familiya):
  """Foydalanuvchining ismini va familiyasini chiqaradi"""
  print(f"Foydalanuvchi ismi: {ism.title()}\n"
        f"Foydalanuvchi familyasi: {familiya.title()}")

In [ ]:
ism_familiya('Ali', 'Valiyev')

Foydalanuvchi ismi: Ali
Foydalanuvchi familyasi: Valiyev


# **Yangi funksiya**

In [ ]:
def yosh_hisobla(ism, tugilgan_yil):
  """Foydalanuvchi yoshini hisoblaydigan dastur"""
  print(f"{ism.title()} {2026-tugilgan_yil} yoshda")

In [ ]:
yosh_hisobla('Saman', 2004)

# Bunda agar ism va yilini almashtirib yozganimizda xato chiqarar edi
# Bunday xatoni oldini olish uchun pastda boshqa metoddan foydalandik

Saman 22 yoshda


In [ ]:
yosh_hisobla(tugilgan_yil=1998, ism='Saman')
# Bunday dict qilib joyini almashtirib yozsak ham to'g'ri chiqaradi

Saman 28 yoshda


In [ ]:
ism_familiya(familiya="Qosimov", ism='Javohir')

Foydalanuvchi ismi: Javohir
Foydalanuvchi familyasi: Qosimov


## **yangi funksiya**

In [ ]:
def yosh_hisob(tugilgan_yil, joriy_yil=2026):
  """Foydalanuvchi yoshini hisoblaydigan dastur"""
  print(f"Siz {joriy_yil-tugilgan_yil} yoshdasiz")

In [ ]:
yosh_hisob(1997)

Siz 29 yoshdasiz


# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **1-AMALIY VAZIFA**

## N-o'lchamli massivlar yaratish

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish

**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning.

**Funksiya yaratilishi haqida darslik:** [bog'lanma](https://www.youtube.com/watch?v=_aDyBPYAeyU&list=PLwsopmzfbOn9Lw5D7a26THpBDgAma1Sus&index=22)


In [3]:
# JAVOBNI SHU YERGA YOZING
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  return np.random.randint(0, 100, size=n)

  # random bilan 0 dan 100 gacha bo'lgan n ta son chiqaradi

In [4]:
print(one_dim(5))
# n o'rniga nechchi son yozsak shuncha shuncha son chiqaradi 0 dan 100 gacha.

[73 92 13 22 56]


In [5]:
one_dim(10)

array([93,  5,  7, 47, 50, 50, 60, 20,  1, 14])

### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [7]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

_____

### Masala(2) 2-o'lchamli massivlar yaratish

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.


In [19]:
# JAVOBNI SHU YERGA YOZING
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    #return np.random.randint([10, 20], [20, 30], size=(r, c))
    return np.random.randint(10, 30, size=(r, c))


In [20]:
two_dim(9, 8)

array([[16, 22, 15, 16, 11, 25, 11, 14],
       [15, 15, 26, 11, 25, 15, 26, 25],
       [29, 27, 13, 22, 22, 11, 26, 28],
       [20, 13, 29, 19, 11, 28, 14, 17],
       [20, 10, 25, 21, 25, 20, 27, 16],
       [27, 21, 29, 26, 29, 14, 15, 15],
       [13, 22, 28, 26, 25, 28, 12, 22],
       [25, 16, 19, 10, 25, 17, 15, 12],
       [12, 12, 26, 28, 17, 25, 25, 24]])

In [ ]:
two_dim(2,2)

### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [21]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array