<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/14_work_with_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPyni chaqirib olamiz

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Bu bilan fayl qilib saqlayabmiz
np.save('data', arr)

In [ ]:
# load bilan shu faylni o'qish mumkin
arr2 = np.load('data.npy')

In [ ]:
arr2 # load bilan arr2 degan o'zgaruvchida o'qiyabmiz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(20) # yangi arr1 massivi

In [ ]:
np.savez('arrays', a=arr, b=arr1) # savez bilan bitta fayl ichida 2 ta arr va arr1 degan massivni saqlayabmiz

In [ ]:
arrays = np.load('arrays.npz')

In [ ]:
arrays['a'] # alohida qilib arr ni o'zini o'qiyabmiz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b'] # Bunda arr1 ni o'qiyabmiz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1) # savez_compressed bilan faylni zip qilib
# yani siqib hajmini kichraytirib saqlashimiz mumkin