<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/5_Indexing_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# N-o'lchovli massiv (array)larga ishlov berish

## Indeks va kesib olish asoslari

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[0] # Bunda indekslar 0 dan boshlanadi.

np.int64(10)

In [ ]:
arr[-2] # teskarisiga yani minus -1 dan boshlanadi

np.int64(80)

In [ ]:
arr[3:6] # Bunda 3 dan 5 gacha indexlarni kesib chiqaradi

array([40, 50, 60])

## Numpy kutubxonasida massivning kesib olingan qismiga o'zgartirish kiritilsa, asosiy manba massivga tasir qiladi.

In [ ]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr = arr[3:5] # Bunda sliced_arr o'zgaruvchiga 3 dan 5 gacha indexlarni yuklayabmiz
sliced_arr[:] = 0 # Va [:] Bu orqali shu hamma 3 dan 5 gacha indexni 0 teng qilib o'zgartirayabmiz
sliced_arr

array([0, 0])

In [ ]:
arr # Hamda yuqorida sliced_arr ga o'zgartirish kiritganimiz asosiy arr ro'yxatga ham tasir qiladi

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

## Copy usuli haqida

In [ ]:
arr1 = np.arange(10, 100, 5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
sliced_arr1 = arr1[3:5].copy() # Bunda copy buyrug'i bilan asosiy ro'yxatga tasir qilmaydi
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [ ]:
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

## 2 o'lchamli (2d array) massivlarda index va kesib olish

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) olchamli massiv

In [ ]:
arr2d # Bunda ham qator va indexlar 0 dan boshlanadi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[1, 1] # Bunda qator indexi ham 0 dan boshlangani uchun 1 bilan 2 qatorga(qavsga) o'tayabdi va uning ichidagi 1 index o'rnida 5 turibdi

np.int64(5)

In [ ]:
arr2d[2, 2]

np.int64(9)

In [ ]:
arr2d[0, 2]

np.int64(3)

In [ ]:
arr2d[-1, -2] # teskarisiga esa index -1 dan boshlanadi

np.int64(8)

## 2-o'lchamli massivlarning bir nechta elementlarini kesib olish

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sl_arr2d = arr2d[2, 1:3]
sl_arr2d

array([8, 9])

In [ ]:
sl_arr2d = arr2d[2, 1:].copy() # Bunda copy() bilan arr2d ga o'zgarishlarni tasir qildirmaymiz
sl_arr2d[:] = 0

In [ ]:
sl_arr2d

array([0, 0])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3- o'lchamli massivlarda index va kesib olish asoslari

In [ ]:
# 3D array
arr3d = np.array([[[ 0, 1, 2],
                   [ 3, 4, 5],
                   [ 6, 7, 8]],

                  [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr3d[0][1, 1:]

array([4, 5])

In [ ]:
arr3d[2][1, 2]

np.int64(23)

In [ ]:
arr3d[2][1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [ ]:
arr3d_new = np.arange(1, 9, 1).reshape(2, 2, 2) # Bunda reshape bilan 3 o'lchamli massiv yaratildi
print("3 o'lchamli massiv:\n", arr3d_new)
print("Massivning o'lchami (shape):", arr3d_new.shape)
arr3d_new.ndim

3 o'lchamli massiv:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Massivning o'lchami (shape): (2, 2, 2)


3