<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/6_Boolean_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
## **malumotlar tahlili**
## 2.1. NumPy Kutubxonasi bilan ishlash

In [31]:
import numpy as np

# **2.1**.1. N-o'lchovli massiv (array)larga ishlov berish
# Bolean indekslash

In [32]:
# ismlar
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [33]:
# data
data = np.random.randn(7, 4) # Bu 7 qator va har qatorda 4 tadan malumot yaratadi
data

array([[ 2.37623827, -1.58960805,  2.03814018, -1.74919047],
       [ 0.77633827,  0.93110123,  0.39133019,  0.06627759],
       [-0.52310897, -0.42492464,  0.09307851, -0.62297808],
       [ 1.48357142,  0.65027577, -0.70540361, -1.30983184],
       [ 1.18542304, -0.41819939, -1.08026046, -1.46824177],
       [-0.58444265,  0.54614085,  0.15695673, -0.90839347],
       [-0.38367603, -0.74118123, -1.56026308,  0.23329596]])

In [34]:
names == 'Hasan' # Ismlarda 2 ta hasan bo'lgani uchun 2 ta True bor

array([ True, False, False, False,  True, False, False])

In [35]:
data[names == 'Hasan'] # Hasanlarga tegishli barcha malumotlarni ajratib oladi

array([[ 2.37623827, -1.58960805,  2.03814018, -1.74919047],
       [ 1.18542304, -0.41819939, -1.08026046, -1.46824177]])

In [36]:
data[names == 'Elyor']

array([[ 1.48357142,  0.65027577, -0.70540361, -1.30983184],
       [-0.38367603, -0.74118123, -1.56026308,  0.23329596]])

In [37]:
data[names == 'Husan'] # Bunda husan ga tegishli malumotlar chiqadi

array([[0.77633827, 0.93110123, 0.39133019, 0.06627759]])

In [38]:
data[names == 'Husan', 2:] # Husan ga tegishli oxirgi 2 ta malumotni chiqarib olish

array([[0.39133019, 0.06627759]])

In [39]:
data[names != 'Hasan'] # Hasandan tashqari boshqa barcha odamlarning malumotini chiqarish

array([[ 0.77633827,  0.93110123,  0.39133019,  0.06627759],
       [-0.52310897, -0.42492464,  0.09307851, -0.62297808],
       [ 1.48357142,  0.65027577, -0.70540361, -1.30983184],
       [-0.58444265,  0.54614085,  0.15695673, -0.90839347],
       [-0.38367603, -0.74118123, -1.56026308,  0.23329596]])

In [40]:
data[~(names == 'Hasan')] # Bu ham yuqoridagi buyruq bilan bir xil vazifani bajaradi

array([[ 0.77633827,  0.93110123,  0.39133019,  0.06627759],
       [-0.52310897, -0.42492464,  0.09307851, -0.62297808],
       [ 1.48357142,  0.65027577, -0.70540361, -1.30983184],
       [-0.58444265,  0.54614085,  0.15695673, -0.90839347],
       [-0.38367603, -0.74118123, -1.56026308,  0.23329596]])

In [41]:
print(names)
print(data)

['Hasan' 'Husan' 'Javohir' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 2.37623827 -1.58960805  2.03814018 -1.74919047]
 [ 0.77633827  0.93110123  0.39133019  0.06627759]
 [-0.52310897 -0.42492464  0.09307851 -0.62297808]
 [ 1.48357142  0.65027577 -0.70540361 -1.30983184]
 [ 1.18542304 -0.41819939 -1.08026046 -1.46824177]
 [-0.58444265  0.54614085  0.15695673 -0.90839347]
 [-0.38367603 -0.74118123 -1.56026308  0.23329596]]


In [42]:
ikkiism = (names == 'Hasan') | (names == 'Husan') # "|" - or (yoki) degan manoni anglatadi
ikkiism # Bunda hasan va husan bor joylar True bilan chiqadi

array([ True,  True, False, False,  True, False, False])

In [43]:
data[ikkiism] # Hasan va Husan ga tegishli malumotlarni ajratib oladi

array([[ 2.37623827, -1.58960805,  2.03814018, -1.74919047],
       [ 0.77633827,  0.93110123,  0.39133019,  0.06627759],
       [ 1.18542304, -0.41819939, -1.08026046, -1.46824177]])

In [47]:
data[data<0] # Bunda 0 dan kichik malumotlarni chiqaradi

array([-1.58960805, -1.74919047, -0.52310897, -0.42492464, -0.62297808,
       -0.70540361, -1.30983184, -0.41819939, -1.08026046, -1.46824177,
       -0.58444265, -0.90839347, -0.38367603, -0.74118123, -1.56026308])

In [49]:
data[data<0] = 0 # Bunda 0 dan kichik sonlarni 0 ga tenglab qaytadan malumotlarni chiqaramiz
data

array([[2.37623827, 0.        , 2.03814018, 0.        ],
       [0.77633827, 0.93110123, 0.39133019, 0.06627759],
       [0.        , 0.        , 0.09307851, 0.        ],
       [1.48357142, 0.65027577, 0.        , 0.        ],
       [1.18542304, 0.        , 0.        , 0.        ],
       [0.        , 0.54614085, 0.15695673, 0.        ],
       [0.        , 0.        , 0.        , 0.23329596]])