<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/7_Transposing_swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

# N-o'lchovli massiv (array)larga ishlov berish

## Massivlar pozitsiyasini ko'chirish transpose va o'qlar o'rnini almashtirish Swapping axes

In [ ]:
A = np.arange(6).reshape(3, 2) # A massive : Elementlari 0~6 gacha, shape (3, 2) yani reshape bilan vertikal 3 qator, gorizantal 2 qator degani
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# Transposening vazifasi gorizantalni vertikal qilib tahlaydi, va ko'pi bilan 2 massivlargacha bu amal ishlaydi
A.T #  Bu yerda T - Transpose degani yani massivning Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

## Swaping axes

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.swapaxes(1, 0) # A massivning Transpose ko'rinishi beradi, Bu usul bilan hohlagancha massivni transpose qila olamiz

array([[0, 2, 4],
       [1, 3, 5]])

## Transposening ishlatilinishiga bir misol AA,T Bunda T AA ning darajasida

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.dot(A, A.T) # AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

🟩 A · Aᵀ jarayoni qisqa ta’rif

A ning har bir satri
×
Aᵀ ning har bir ustuni

➡ elementma-element ko‘paytiriladi va yig‘iladi.
Natijada yangi kvadrat matrisa hosil bo‘ladi.

Yana qisqaroq:

✅ “Satr · Ustun = Yangi element”

Yana ham qisqa:

⚡ “Satrlar va ustunlar o‘zaro ko‘payib yangi matrisa beradi.”