<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/9_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy kutubxonasini chaqirib olamiz

In [ ]:
import numpy as np

# Massivga yo'naltirilgan dasturlash

## Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

## Shart operatori sifatida where dan foydalanish

## Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: xarr va yarr. Agarda shart True ni qanoatlantirsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massiv hosil qilinsin

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementini chiqaradi, va buni np.where buyrug'i orqali qilamiz.
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

## New example with where

In [ ]:
arr = np.random.randn(4, 4) # (4, 4) taxminiy massiv
arr

array([[ 1.4360469 ,  1.60000753,  0.81930798, -0.85736371],
       [ 0.95411213,  0.77436203, -0.77199651,  1.02301504],
       [ 1.50256533, -0.37444804, -0.00605532, -0.81758531],
       [ 1.40959294,  1.96829292, -0.5596083 , -1.19409029]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarini esa 2 ga almashtirildi
results

array([[ 2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

## New example with where

In [ ]:
ism = np.array(['shokir', 'tora', '2004 - ', 'dimka', 'tugilgan'])
familya = np.array(['qosimov', 'abduvaliyev', 'kunda', 'yilda', 'ha'])


In [ ]:
shart = np.array([True, False, True, False, True])

In [ ]:
natija = np.where(shart, ism, familya)
print(natija)

['shokir' 'abduvaliyev' '2004 - ' 'yilda' 'tugilgan']
