<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/array_in_massiv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonasini chaqirib olish

In [ ]:
import numpy as np


# N-o'lchovli massiv (array)larga ishlov berish

Numpyda massiv yaratishning eng osson yo'llardan biri bu array funksiyasi yordamida amalga oshiroladi. Va ushbu funksiya harqanday turdagi ketma-ket malumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi

In [ ]:
data1 = [3.5, 6, 2, 9] # list
arr1 = np.array(data1) # array1

In [ ]:
data1

[3.5, 6, 2, 9]

In [ ]:
arr1

array([3.5, 6. , 2. , 9. ])

In [ ]:
data2 = (4, 2, 7.3, 5) # tuple
arr2 = np.array(data2) # array2

In [ ]:
data2

(4, 2, 7.3, 5)

In [ ]:
arr2

array([4. , 2. , 7.3, 5. ])

Massiv o'lchami

In [ ]:
arr1.ndim # array1 ning o'lchami yani bunda ndim bilan massiv o'lchovi aniqlanadi

1

In [ ]:
arr2.ndim # array2 ning o'lchami

1

ikki va undan katta o'lchamli massivlar

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3) # array3

In [ ]:
arr3.ndim

2

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Uch o'lchovli massiv

In [ ]:
data4 = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
arr4 = np.array(data4)
display(arr4)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr4.ndim

3

In [ ]:
import numpy as np

arr_example = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
display(arr_example)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
print(arr_example.shape)

(2, 4)


In [ ]:
arr3.shape # qator va ustunlar sonini ko'rsatadi (q, u)

(2, 4)

In [ ]:
arr3.size # array3 ning elementlar soni

8

# N-o'lchovli massivlar yaratishning boshqa **usullari**

zeros va ones funksiyalari yordamida massivlar yaratish

In [ ]:
arr5 = np.zeros((2, 4)) # barcha elementlar 0 ga teng (2, 4)
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((2, 4)) # barcha elementlar 1 ga teng (2, 4)
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arrange funksiyasi yordamida yaratish

In [ ]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha sonlarni 2 qadamlab chiqaradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8 = np.arange(20) # 0 dan 20 gacha 1 qadamlab chiqaradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
import numpy as np

# empty funksiyasi - o'rnatilgan qiymatlarsiz, lekin ko'rsatilgan shaklga ega massiv yaratadi.
# Dastlabki qiymatlar xotirada mavjud bo'lgan narsalar bo'ladi (tasodifiy raqamlar emas).
arr_empty = np.empty((2, 3))
print("np.empty((2, 3)):\n", arr_empty)

# full funksiyasi - berilgan qiymat bilan to'ldirilgan massiv yaratadi.
arr_full = np.full((3, 2), 7) # 3 qator, 2 ustun, barcha elementlar 7
print("\nnp.full((3, 2), 7):\n", arr_full)

# eye funksiyasi - diagonalda birlar va boshqa joylarda nollar bo'lgan ikki o'lchovli massiv (identifikatsiya matritsasi) yaratadi.
arr_eye = np.eye(4) # 4x4 identifikatsiya matritsasi
print("\nnp.eye(4):\n", arr_eye)

# identity funksiyasi - eye bilan bir xil, kvadrat identifikatsiya matritsasi yaratadi.
arr_identity = np.identity(3) # 3x3 identifikatsiya matritsasi
print("\nnp.identity(3):\n", arr_identity)

# linspace funksiyasi - berilgan oraliqda bir tekis joylashgan raqamlar ketma-ketligini yaratadi.
arr_linspace = np.linspace(0, 10, 5) # 0 dan 10 gacha 5 ta son
print("\nnp.linspace(0, 10, 5):\n", arr_linspace)

# random.rand funksiyasi - 0 dan 1 gacha bo'lgan tasodifiy sonlar massivini yaratadi.
arr_rand = np.random.rand(2, 2) # 2x2 tasodifiy sonlar massivi
print("\nnp.random.rand(2, 2):\n", arr_rand)


np.empty((2, 3)):
 [[2.32184786e-315 0.00000000e+000 2.33419537e-312]
 [2.22809558e-312 2.14321575e-312 1.06477489e-166]]

np.full((3, 2), 7):
 [[7 7]
 [7 7]
 [7 7]]

np.eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.identity(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.linspace(0, 10, 5):
 [ 0.   2.5  5.   7.5 10. ]

np.random.rand(2, 2):
 [[0.39923236 0.02035389]
 [0.93623466 0.04811339]]
