<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Massivlar yaratishda ma'lumot turlarini aniq kiritish, ma'lumot turlarini aniqlash, bir turdagi ma'lumot turidan ikkinchi turdagi ma'lumot turiga o'girish

In [ ]:
arr1 = np.array([1, 2, 3, 4], dtype=np.float64) # Bu float64 ma'lumotlar turiga ega massiv
arr1

array([1., 2., 3., 4.])

In [ ]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int32) # Bu int32 ma'lumotlar turiga ega massiv
arr2

array([1, 2, 3, 4, 5], dtype=int32)

## dtype metodi

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

Bir turdagi malumot turidan boshqasiga o'girish

In [ ]:
arr = np.array([1, 2, 3, 4]) # int64 bo'ladi agar hech qanday dtypeni aytmasak
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

astype metodi

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
data = np.array([3.7, -1.2, -2.6, 5]) # float64 bo'ladi avtomatiskiy
data.dtype

dtype('float64')

In [ ]:
int_data = data.astype(np.int64) # Bunda int dan floatga o'zgartirganda faqat butun sonni oladi va lekin turi o'zgaradi
int_data

array([ 3, -1, -2,  5])

### NumPy ma'lumot turlari (dtypes)

In [ ]:
import numpy as np

# Integer turlari
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
print(f"int8: {arr_int8.dtype}")

arr_int16 = np.array([1, 2, 3], dtype=np.int16)
print(f"int16: {arr_int16.dtype}")

arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print(f"int32: {arr_int32.dtype}")

arr_int64 = np.array([1, 2, 3], dtype=np.int64)
print(f"int64: {arr_int64.dtype}")

# Float turlari
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(f"float32: {arr_float32.dtype}")

arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(f"float64: {arr_float64.dtype}")

# Boolean turi
arr_bool = np.array([True, False, True], dtype=np.bool_)
print(f"bool: {arr_bool.dtype}")

# String turi
arr_str = np.array(['hello', 'world'], dtype=np.str_)
print(f"string: {arr_str.dtype}")

# Complex turi
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex64)
print(f"complex64: {arr_complex.dtype}")

arr_complex128 = np.array([1+2j, 3+4j], dtype=np.complex128)
print(f"complex128: {arr_complex128.dtype}")

int8: int8
int16: int16
int32: int32
int64: int64
float32: float32
float64: float64
bool: bool
string: <U5
complex64: complex64
complex128: complex128


Bu eng ko'p ishlatiladigan ma'lumot turlaridan ba'zilari. Har bir tur ma'lumotni saqlash uchun turli miqdordagi xotiradan foydalanadi va ularning chegaralari bor (masalan, `int8` kichikroq sonlarni saqlay oladi, `int64` esa juda katta sonlarni).