<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/Takrorlash_NumPy_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.__version__
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [ ]:
numbers = np.array([1,2,3,4,5])
print(numbers)

[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
zero = np.zeros(9)
print(zero)

one = np.size(zero)
print(f"Size ({one})")

two = zero.itemsize
print(f"Xotira hajmi ({two}) ekan")


[0. 0. 0. 0. 0. 0. 0. 0. 0.]
Size (9)
Xotira hajmi (8) ekan


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
#import numpy as np
#help(np.add)
np.info(np.add)
a = np.arange(1, 10)
a
b = np.arange(1, 10)
b
np.add(a, b)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [ ]:
vektor = np.zeros(12)
vektor[5] = 1
print(vektor)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [ ]:
vektor1 = np.arange(20, 60)
print(vektor1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [ ]:
vektor2 = np.arange(1, 11)
print(vektor2)
print(vektor2[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
matrissa = np.arange(12, 21)
matrissa.reshape(3, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
index = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(index)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
massiv = np.random.random((2, 2, 2))
print(massiv)

[[[0.10780214 0.16505569]
  [0.69139879 0.40484759]]

 [[0.03999361 0.64261612]
  [0.52597165 0.3933055 ]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [ ]:
minmax = np.random.random((9, 9))
print(minmax)
print(np.min(minmax))
print(np.max(minmax))

[[0.75143615 0.49851363 0.96615552 0.89936975 0.33684379 0.65341247
  0.31145069 0.3502375  0.9473033 ]
 [0.51790887 0.33170491 0.69346953 0.83422262 0.65826583 0.76234667
  0.60616434 0.05414885 0.20872891]
 [0.65182633 0.23564413 0.23201767 0.12260826 0.74690058 0.01257977
  0.73931306 0.81401154 0.8972619 ]
 [0.14832458 0.10930985 0.12902988 0.29171987 0.86060513 0.96499948
  0.69533822 0.04166198 0.01277792]
 [0.63135884 0.74092696 0.03605231 0.62248866 0.49919271 0.06383512
  0.99962084 0.098874   0.53956473]
 [0.79847545 0.6140062  0.79321904 0.97387502 0.41004968 0.83814982
  0.97885581 0.22868341 0.0931691 ]
 [0.02373387 0.47620196 0.84050092 0.91044562 0.52295569 0.45221672
  0.45868836 0.7596981  0.62263986]
 [0.9251639  0.86932457 0.34032404 0.53706975 0.419346   0.10974551
  0.32508526 0.14324277 0.92344686]
 [0.47584335 0.8217911  0.28722727 0.75996931 0.40645346 0.46837073
  0.98696712 0.2915807  0.77488137]]
0.01257976606211575
0.9996208354011364


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
False

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr = np.arange(1, 19).reshape(6, 3)
arr1 = np.arange(1, 13).reshape(3, 4)
print(arr)
print(arr1)
print(np.dot(arr, arr1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]
 [218 260 302 344]
 [263 314 365 416]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # bunda hammasi qo'shiladi -1 ham
from numpy import *
print(sum(range(5),-1)) # axis = -1 → oxirgi o‘q bo‘yicha yig‘iladi.

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 9, 2])
b = np.array([2, 10, 2])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False False]
[False False  True]
[ True  True False]
[ True  True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [ ]:
masiv = np.arange(1, 10)
masiv1 = np.arange(5, 14)
np.intersect1d(masiv, masiv1)

array([5, 6, 7, 8, 9])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
data = np.array([1.1, 2.2, 3.3,])
print(data)
print(data - data % 1)
print(np.floor(data))
print(data.astype(int))
print(np.trunc(data))

[1.1 2.2 3.3]
[1. 2. 3.]
[1. 2. 3.]
[1 2 3]
[1. 2. 3.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [ ]:
data1 = np.arange(0, 9).reshape(3, 3)
data1 % 3

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
data3 = np.arange(1, 11)
np.sort(data3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a = np.arange(1, 10)
b = np.arange(1, 10)
c = np.arange(10, 100, 10)
d = np.arange(10, 150, 15)
print(np.allclose(a, b))
np.array_equal(c, d)

True


False

#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
one = np.arange(1, 19).reshape(6, 3)
two = np.arange(1, 13).reshape(3, 4)
print(one)
print(two)
np.dot(one, two)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272],
       [218, 260, 302, 344],
       [263, 314, 365, 416]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [ ]:
data = np.arange(1, 6)
print(data)
data[np.argmax(data)] = 0
print(data)

[1 2 3 4 5]
[1 2 3 4 0]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
kechadan_avval = np.datetime64('today', 'D') - np.timedelta64(2, 'D')
kecha = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
bugun = np.datetime64('today', 'D')
ertaga = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
ettadan_keyin = np.datetime64('today', 'D') + np.timedelta64(2, 'D')
print(kechadan_avval)
print(kecha)
print(bugun)
print(ertaga)
print(ettadan_keyin)

2025-12-02
2025-12-03
2025-12-04
2025-12-05
2025-12-06


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
yanvar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print(yanvar)


['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
musbat = np.array([1.1, 2.2, 3.3,])
print(musbat)
print(musbat - musbat % 1)
print(np.floor(musbat))
print(musbat.astype)
print(np.trunc(musbat))

[1.1 2.2 3.3]
[1. 2. 3.]
[1. 2. 3.]
<built-in method astype of numpy.ndarray object at 0x7cbbd3e34390>
[1. 2. 3.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
data = np.arange(1, 10)
np.add.reduce(data)

np.int64(45)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# Har bir element uchun 3 ta nol joy ajratamiz (1 element = 4 ta joy)
result = np.zeros(len(a) * 4, dtype=int)

# Har 4-chi joyga elementlarni joylaymiz
result[::4] = a

print(result)



[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [ ]:

a = np.arange(1, 15)
b = np.lib.stride_tricks.as_strided(
    a,
    shape=(11, 4),          # 11 ta qator, har birida 4 ta element
    strides=(a.strides[0], a.strides[0])
)
print(a)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
import numpy as np

# Ixtiyoriy massiv
data = np.array([1, 3, 5, 3, 7, 3, 5, 1, 5, 5, 7, 7, 7, 7])

# Har bir son necha marta uchrashganini hisoblaymiz
counts = np.bincount(data)

# Eng ko‘p uchragan element
most_common = np.argmax(counts)

print("Massiv:", data)
print("Takrorlanishlar:", counts)
print("Eng ko‘p uchragan qiymat:", most_common)
print("Uchrash soni:", counts[most_common])


Massiv: [1 3 5 3 7 3 5 1 5 5 7 7 7 7]
Takrorlanishlar: [0 2 0 3 0 4 0 5]
Eng ko‘p uchragan qiymat: 7
Uchrash soni: 5


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

In [ ]:
import numpy as np
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr


# Shart
cond = np.array([True, False, True, True, False])


# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementini chiqaradi, va buni np.where buyrug'i orqali qilamiz.
print(result)
