<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/12_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

# **Massivga yo'naltirilgan dasturlash**

## Tartiblash (Sorting)

In [ ]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.70591222, 0.20837437, 0.27430063, 0.44900245])

## sort funksiyasi

In [ ]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivining tartiblangan versiyasi
sorted_arr # Bu buytuq bilan kichikdan katta raqamga o'sib boradi

array([0.20837437, 0.27430063, 0.44900245, 0.70591222])

In [ ]:
# 2 usul
arr.sort() # arr ning tartiblangan ko'rinishi
arr

array([0.20837437, 0.27430063, 0.44900245, 0.70591222])

In [ ]:
# Teskari tartiblash yani kattadan kichikga kamayib boradi
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.70591222, 0.44900245, 0.27430063, 0.20837437])

In [ ]:
# 2 D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[-0.72411406,  1.24981419, -1.83071914, -1.39193558],
       [-0.71931993,  1.55024908,  1.53153662, -1.40792535]])

In [ ]:
# axis = 0 --> Qator
row_sort = np.sort(arr2d, axis=0) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi yani vertikal bo'yicha.
row_sort

array([[-0.72411406,  1.24981419, -1.83071914, -1.40792535],
       [-0.71931993,  1.55024908,  1.53153662, -1.39193558]])

In [ ]:
# axis = 1 --> Ustun yani gorizontal tartibda
col_srt = np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi yani gorizantal
col_srt

array([[-1.83071914, -1.39193558, -0.72411406,  1.24981419],
       [-1.40792535, -0.71931993,  1.53153662,  1.55024908]])

In [ ]:
# Bu pastagi kattadan kichikga qarab boradi

In [ ]:
col_srt = -np.sort(-arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi yani gorizantal
col_srt

array([[ 1.24981419, -0.72411406, -1.39193558, -1.83071914],
       [ 1.55024908,  1.53153662, -0.71931993, -1.40792535]])