<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/15_Chiziqli_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Ma'lumotlar tahlili. NumPy kutubxonasi**

## Chiziqli algebra

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
y = np.array([[5., 5., 5.], [4., 4., 4.]])

In [ ]:
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [ ]:
x+y # matritsalarni qo'shish

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [ ]:
y-x # y matritsasida x matrissasini ayirish

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [ ]:
x*y

array([[ 5., 10., 15.],
       [16., 20., 24.]])

In [ ]:
#                     ---->  \/  <----

### Matritsalarni ko'paytirishda, birinchi matritsaning ustunlar soni ikkinchi matritsaning qatorlar soniga teng bo'lishi kerak. `x` (2x3) va `y` (2x3) massivlari to'g'ridan-to'g'ri matritsa ko'paytirilishi uchun mos kelmaydi (chunki x ning ustunlari soni y ning qatorlari soniga teng emas).

In [ ]:
# Bunda yani qanday amal kechadi har birini mos ravishda alohida qilib ko'paytiradi va umumiy ko'paytmalarni hammasini qo'shadi
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [ ]:
x.dot(y) # x*y

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
np.dot(x,y) # x*y Bu ham shu ko'paytirish amalini bajaradi

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
y.dot(x) # y*x

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [ ]:
np.dot(y,x) # y*x

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

## New section

In [ ]:
# Linear Algebra
from numpy.linalg import inv

### Qo'shimcha Matritsa Ko'paytirish Misollari

**1-misol:** 1x3 matritsani 3x1 matritsaga ko'paytirish.

In [ ]:
a = np.array([[1, 2, 3]]) # 1x3 matritsa
b = np.array([[4], [5], [6]]) # 3x1 matritsa

print('a matritsasi:')
print(a)
print('\nb matritsasi:')
print(b)

# Natija 1x1 matritsa bo'ladi
result1 = np.dot(a, b)
print('\na * b (np.dot) natijasi:')
print(result1)

a matritsasi:
[[1 2 3]]

b matritsasi:
[[4]
 [5]
 [6]]

a * b (np.dot) natijasi:
[[32]]


**2-misol:** 2x2 matritsani 2x2 matritsaga ko'paytirish.

In [ ]:
c = np.array([[1, 0], [0, 1]]) # 2x2 birlik matritsa
d = np.array([[2, 3], [4, 5]]) # 2x2 matritsa

print('c matritsasi:')
print(c)
print('\nd matritsasi:')
print(d)

# Natija 2x2 matritsa bo'ladi
result2 = np.dot(c, d)
print('\nc * d (np.dot) natijasi:')
print(result2)

# '@' operatori bilan ham shu ishni qilish mumkin
result2_at = c @ d
print('\nc @ d natijasi:')
print(result2_at)

c matritsasi:
[[1 0]
 [0 1]]

d matritsasi:
[[2 3]
 [4 5]]

c * d (np.dot) natijasi:
[[2 3]
 [4 5]]

c @ d natijasi:
[[2 3]
 [4 5]]


**3-misol:** 2x3 matritsani 3x2 matritsaga ko'paytirish.

In [ ]:
e = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 matritsa
f = np.array([[7, 8], [9, 10], [11, 12]]) # 3x2 matritsa

print('e matritsasi:')
print(e)
print('\nf matritsasi:')
print(f)

# Natija 2x2 matritsa bo'ladi
result3 = np.dot(e, f)
print('\ne * f (np.dot) natijasi:')
print(result3)

e matritsasi:
[[1 2 3]
 [4 5 6]]

f matritsasi:
[[ 7  8]
 [ 9 10]
 [11 12]]

e * f (np.dot) natijasi:
[[ 58  64]
 [139 154]]
