<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/8_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy kutubxonasini chaqirib olamiz

In [ ]:
import numpy as np

# Universal funksiyalar

## Unary funksiyalar (bitta argument qabul qiluvchi funksiya)

## sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz

In [ ]:
arr = np.arange(10) # 0 ~ 10 gacha bo'lgan elementlardan iborat massivni qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## sqrt massivning xar bir elementini kvadrat ildizini qaytaradi

In [ ]:
np.sqrt(arr) # arr nomli massivning barcha elementini kvadratga oshiradi. Hamda unary bo'lgani uchun bitta o'zgaruvchi qiymatini oladi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## square massivning xar bir elementini kvadratga oshiradi

In [ ]:
np.square(arr)# arr nomli massivning barcha elementini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## exp massivning xar bir elementini kvadratga oshiradi

In [ ]:
np.exp(arr) # arr nomli massivning barcha elementlarini eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## log massivning xar bir logorifimini hisoblaydi

In [ ]:
np.log(arr) # arr nomli massivning barcha elementini logarifimini hisoblaydi(loga)

/tmp/ipython-input-4269585573.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # arr nomli massivning barcha elementini logarifimini hisoblaydi(loga)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.log(arr[1:]) # Bu bilan 0 xato bergani uchun qaytadan 1 dan boshladik

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

## modf bu funksiya haqiqiy sonlarni butun va qoldiq qismlarini ajratib beruvchi funksiya

In [ ]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([-0.4480137 , -0.50162179,  0.49379053, -1.66328918,  1.45146582,
        0.22349588])

In [ ]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi

In [ ]:
print(qoldiq)
print(butun)

[-0.4480137  -0.50162179  0.49379053 -0.66328918  0.45146582  0.22349588]
[-0. -0.  0. -1.  1.  0.]


## sign funksiyasi massiv elementlarini qiymat manfiy bo'lsa -1 va aksincha musbat bo'lsa 1 ni qaytaradi

In [ ]:
arr1

array([-0.4480137 , -0.50162179,  0.49379053, -1.66328918,  1.45146582,
        0.22349588])

In [ ]:
np.sign(arr1) # arr1 massivining elementlari ishoralarini "-1" va "1" ko'rinishida qaytaradi

array([-1., -1.,  1., -1.,  1.,  1.])

## isnan massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa False qaytaradi

In [ ]:
arr1

array([-0.4480137 , -0.50162179,  0.49379053, -1.66328918,  1.45146582,
        0.22349588])

In [ ]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [ ]:
arr1[0] = np.nan # 0 - elementimizni nan ga almashtirdik

In [ ]:
arr1[2] = np.nan # ikkinchi indexda turganni ham nan ga almashtirdik

In [ ]:
arr1

array([        nan, -0.50162179,         nan, -1.66328918,  1.45146582,
        0.22349588])

In [ ]:
np.isnan(arr1)

array([ True, False,  True, False, False, False])

## abs va fabs funksiyalari (absolyut qiymat)

In [ ]:
arr_abs_fabs = np.array([-1.2, 0.5, -3, 4, -0.0])
print(f"Original array for abs/fabs: {arr_abs_fabs}")

Original array for abs/fabs: [-1.2  0.5 -3.   4.  -0. ]


### abs: massiv elementlarining absolyut qiymatini hisoblaydi

In [ ]:
print(f"np.abs(arr_abs_fabs): {np.abs(arr_abs_fabs)}")

np.abs(arr_abs_fabs): [1.2 0.5 3.  4.  0. ]


### fabs: massiv elementlarining absolyut qiymatini float ko'rinishida hisoblaydi

In [ ]:
print(f"np.fabs(arr_abs_fabs): {np.fabs(arr_abs_fabs)}")

np.fabs(arr_abs_fabs): [1.2 0.5 3.  4.  0. ]


## log10 funksiyasi (10 asosli logarifm)

In [ ]:
arr_log10 = np.array([1, 10, 100, 1000])
print(f"Original array for log10: {arr_log10}")

Original array for log10: [   1   10  100 1000]


### log10: massiv elementlarining 10 asosli logarifmini hisoblaydi

In [ ]:
print(f"np.log10(arr_log10): {np.log10(arr_log10)}")

np.log10(arr_log10): [0. 1. 2. 3.]


## ceil, floor, rint funksiyalari (yaxlitlash)

In [ ]:
arr_round_new = np.array([-1.7, -1.5, -1.2, 0.5, 1.2, 1.5, 1.7])
print(f"Original array for rounding: {arr_round_new}")

Original array for rounding: [-1.7 -1.5 -1.2  0.5  1.2  1.5  1.7]


### ceil: massiv elementlarini yuqoriga yaxlitlaydi (ceiling)

In [ ]:
print(f"np.ceil(arr_round_new): {np.ceil(arr_round_new)}")

np.ceil(arr_round_new): [-1. -1. -1.  1.  2.  2.  2.]


### floor: massiv elementlarini pastga yaxlitlaydi (floor)

In [ ]:
print(f"np.floor(arr_round_new): {np.floor(arr_round_new)}")

np.floor(arr_round_new): [-2. -2. -2.  0.  1.  1.  1.]


### rint: massiv elementlarini eng yaqin butun songa yaxlitlaydi

In [ ]:
print(f"np.rint(arr_round_new): {np.rint(arr_round_new)}")

np.rint(arr_round_new): [-2. -2. -1.  0.  1.  2.  2.]


## modf funksiyasi (butun va qoldiq qismlarini ajratish)

In [ ]:
arr_modf = np.array([-3.7, -1.5, 0.9, 2.3])
print(f"Original array for modf: {arr_modf}")
qoldiq_new, butun_new = np.modf(arr_modf)
print(f"Qoldiq (fractional part): {qoldiq_new}")
print(f"Butun (integer part): {butun_new}")

Original array for modf: [-3.7 -1.5  0.9  2.3]
Qoldiq (fractional part): [-0.7 -0.5  0.9  0.3]
Butun (integer part): [-3. -1.  0.  2.]


## Kosinus, Sinus, Tangens va Giperbolik funksiyalar

In [ ]:
arr_trig_new = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2]) # Radiandagi burchaklar
print(f"Original array (radians) for trig functions: {arr_trig_new}")

Original array (radians) for trig functions: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


### cos: massiv elementlarining kosinusini hisoblaydi

In [ ]:
print(f"np.cos(arr_trig_new): {np.cos(arr_trig_new)}")

np.cos(arr_trig_new): [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


### cosh: massiv elementlarining giperbolik kosinusini hisoblaydi

In [ ]:
print(f"np.cosh(arr_trig_new): {np.cosh(arr_trig_new)}")

np.cosh(arr_trig_new): [1.         1.14023832 1.32460909 1.60028686 2.50917848]


### sin: massiv elementlarining sinusini hisoblaydi

In [ ]:
print(f"np.sin(arr_trig_new): {np.sin(arr_trig_new)}")

np.sin(arr_trig_new): [0.         0.5        0.70710678 0.8660254  1.        ]


### sinh: massiv elementlarining giperbolik sinusini hisoblaydi

In [ ]:
print(f"np.sinh(arr_trig_new): {np.sinh(arr_trig_new)}")

np.sinh(arr_trig_new): [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]


### tan: massiv elementlarining tangensini hisoblaydi

In [ ]:
print(f"np.tan(arr_trig_new): {np.tan(arr_trig_new)}")

np.tan(arr_trig_new): [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### tanh: massiv elementlarining giperbolik tangensini hisoblaydi

In [ ]:
print(f"np.tanh(arr_trig_new): {np.tanh(arr_trig_new)}")

np.tanh(arr_trig_new): [0.         0.48047278 0.6557942  0.78071444 0.91715234]


## Binary funksiyalar (ikkita argument qabul qiluvchi funksiyalar)

In [ ]:
# Misollar uchun ikkita massiv yaratib olamiz
arr_a = np.array([10, 20, 30, 40, 50])
arr_b = np.array([3, 5, 2, 8, 10])
print(f"arr_a: {arr_a}")
print(f"arr_b: {arr_b}")

### subtract: ikkita massivning mos elementlarini ayiradi

In [ ]:
print(f"np.subtract(arr_a, arr_b): {np.subtract(arr_a, arr_b)}")

### power: birinchi massiv elementlarini ikkinchi massiv elementlari darajasiga oshiradi

In [ ]:
print(f"np.power(arr_a, arr_b): {np.power(arr_a, arr_b)}")

### maximum: ikkita massivning mos elementlaridan kattasini qaytaradi

In [ ]:
print(f"np.maximum(arr_a, arr_b): {np.maximum(arr_a, arr_b)}")

### fmax: ikkita massivning mos elementlaridan kattasini qaytaradi, NaN qiymatlarni e'tiborsiz qoldiradi

In [ ]:
arr_c = np.array([1, np.nan, 3, 4])
arr_d = np.array([np.nan, 2, 1, 5])
print(f"arr_c: {arr_c}")
print(f"arr_d: {arr_d}")
print(f"np.fmax(arr_c, arr_d): {np.fmax(arr_c, arr_d)}")

### minimum: ikkita massivning mos elementlaridan kichigini qaytaradi

In [ ]:
print(f"np.minimum(arr_a, arr_b): {np.minimum(arr_a, arr_b)}")

### fmin: ikkita massivning mos elementlaridan kichigini qaytaradi, NaN qiymatlarni e'tiborsiz qoldiradi

In [ ]:
print(f"np.fmin(arr_c, arr_d): {np.fmin(arr_c, arr_d)}")

### mod: ikkita massivning mos elementlari bo'linmasining qoldig'ini qaytaradi

In [ ]:
print(f"np.mod(arr_a, arr_b): {np.mod(arr_a, arr_b)}")

### copysign: birinchi massiv elementlarining absolyut qiymatiga ikkinchi massiv elementlarining ishorasini qo'yadi

In [ ]:
arr_e = np.array([1.0, -2.0, 3.0, -4.0])
arr_f = np.array([-1.0, 2.0, -3.0, 4.0])
print(f"arr_e: {arr_e}")
print(f"arr_f: {arr_f}")
print(f"np.copysign(arr_e, arr_f): {np.copysign(arr_e, arr_f)}")

## Taqoslash funksiyalari (Comparison functions)

In [ ]:
arr_g = np.array([1, 2, 3, 4, 5])
arr_h = np.array([2, 2, 1, 4, 6])
print(f"arr_g: {arr_g}")
print(f"arr_h: {arr_h}")

### greater: birinchi massiv elementi ikkinchidan katta bo'lsa True qaytaradi

In [ ]:
print(f"np.greater(arr_g, arr_h): {np.greater(arr_g, arr_h)}")

### greater_equal: birinchi massiv elementi ikkinchidan katta yoki teng bo'lsa True qaytaradi

In [ ]:
print(f"np.greater_equal(arr_g, arr_h): {np.greater_equal(arr_g, arr_h)}")

### less: birinchi massiv elementi ikkinchidan kichik bo'lsa True qaytaradi

In [ ]:
print(f"np.less(arr_g, arr_h): {np.less(arr_g, arr_h)}")

### less_equal: birinchi massiv elementi ikkinchidan kichik yoki teng bo'lsa True qaytaradi

In [ ]:
print(f"np.less_equal(arr_g, arr_h): {np.less_equal(arr_g, arr_h)}")

### equal: ikkala massiv elementlari teng bo'lsa True qaytaradi

In [ ]:
print(f"np.equal(arr_g, arr_h): {np.equal(arr_g, arr_h)}")

### not_equal: ikkala massiv elementlari teng bo'lmasa True qaytaradi

In [ ]:
print(f"np.not_equal(arr_g, arr_h): {np.not_equal(arr_g, arr_h)}")

## Mantiqiy funksiyalar (Logical functions)

In [ ]:
arr_bool1 = np.array([True, False, True, False])
arr_bool2 = np.array([True, True, False, False])
print(f"arr_bool1: {arr_bool1}")
print(f"arr_bool2: {arr_bool2}")

### logical_and: ikkala element ham True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_and(arr_bool1, arr_bool2): {np.logical_and(arr_bool1, arr_bool2)}")

### logical_or: elementlardan hech bo'lmaganda bittasi True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_or(arr_bool1, arr_bool2): {np.logical_or(arr_bool1, arr_bool2)}")

### logical_xor: elementlardan faqat bittasi True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_xor(arr_bool1, arr_bool2): {np.logical_xor(arr_bool1, arr_bool2)}")

# Binary funksiyalar (ikkita argument qabul qiluvchi funksiya)

## add, multiply, maximum funksiyalarini ko'rib chiqamiz

## add ikkita massivning mos elementlarini qo'shadi

In [ ]:
# 2 ta massivni yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [ ]:
arr2

array([ 0.92112223, -0.37582177, -1.7964108 , -0.42146274,  0.15942312,
        1.6754742 ])

In [ ]:
arr3

array([-2.05353033,  0.09390847,  1.41867594, -0.01265745,  0.42224507,
        0.21680023])

In [ ]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-1.13240811, -0.28191331, -0.37773486, -0.43412019,  0.58166819,
        1.89227443])

In [ ]:
arr2 + arr3 # Bu ham arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-1.13240811, -0.28191331, -0.37773486, -0.43412019,  0.58166819,
        1.89227443])

## multiply ikkita massivning mos elementlarini ko'paytiradi

In [ ]:
arr2

array([ 0.92112223, -0.37582177, -1.7964108 , -0.42146274,  0.15942312,
        1.6754742 ])

In [ ]:
arr3

array([-2.05353033,  0.09390847,  1.41867594, -0.01265745,  0.42224507,
        0.21680023])

In [ ]:
np.multiply(arr2, arr3) # arr2 va arr3 ning mos elementlarini ko'paytiradi

array([-1.89155243, -0.03529285, -2.54852477,  0.00533464,  0.06731563,
        0.36324319])

In [ ]:
arr2 * arr3 # Bu ham shu ko'paytirish vazifasini bajaradi

array([-1.89155243, -0.03529285, -2.54852477,  0.00533464,  0.06731563,
        0.36324319])

## maximum ikkita massivning elementlarini taqqoslab ulardan kattasining qiymatini qaytaradi

In [ ]:
np.maximum(arr2, arr3) # arr2 va arr3 ning elementlarini taqqoslab kattasini qaytaradi

array([ 0.92112223,  0.09390847,  1.41867594, -0.01265745,  0.42224507,
        1.6754742 ])

## Binary funksiyalar (ikkita argument qabul qiluvchi funksiyalar) davomi

In [ ]:
# Misollar uchun ikkita massiv yaratib olamiz
arr_a = np.array([10, 20, 30, 40, 50])
arr_b = np.array([3, 5, 2, 8, 10])
print(f"arr_a: {arr_a}")
print(f"arr_b: {arr_b}")

arr_a: [10 20 30 40 50]
arr_b: [ 3  5  2  8 10]


### subtract: ikkita massivning mos elementlarini ayiradi

In [ ]:
print(f"np.subtract(arr_a, arr_b): {np.subtract(arr_a, arr_b)}")

np.subtract(arr_a, arr_b): [ 7 15 28 32 40]


### power: birinchi massiv elementlarini ikkinchi massiv elementlari darajasiga oshiradi

In [ ]:
print(f"np.power(arr_a, arr_b): {np.power(arr_a, arr_b)}")

np.power(arr_a, arr_b): [             1000           3200000               900     6553600000000
 97656250000000000]


### maximum: ikkita massivning mos elementlaridan kattasini qaytaradi

In [ ]:
print(f"np.maximum(arr_a, arr_b): {np.maximum(arr_a, arr_b)}")

np.maximum(arr_a, arr_b): [10 20 30 40 50]


### fmax: ikkita massivning mos elementlaridan kattasini qaytaradi, NaN qiymatlarni e'tiborsiz qoldiradi

In [ ]:
arr_c = np.array([1, np.nan, 3, 4])
arr_d = np.array([np.nan, 2, 1, 5])
print(f"arr_c: {arr_c}")
print(f"arr_d: {arr_d}")
print(f"np.fmax(arr_c, arr_d): {np.fmax(arr_c, arr_d)}")

arr_c: [ 1. nan  3.  4.]
arr_d: [nan  2.  1.  5.]
np.fmax(arr_c, arr_d): [1. 2. 3. 5.]


### minimum: ikkita massivning mos elementlaridan kichigini qaytaradi

In [ ]:
print(f"np.minimum(arr_a, arr_b): {np.minimum(arr_a, arr_b)}")

np.minimum(arr_a, arr_b): [ 3  5  2  8 10]


### fmin: ikkita massivning mos elementlaridan kichigini qaytaradi, NaN qiymatlarni e'tiborsiz qoldiradi

In [ ]:
print(f"np.fmin(arr_c, arr_d): {np.fmin(arr_c, arr_d)}")

np.fmin(arr_c, arr_d): [1. 2. 1. 4.]


### mod: ikkita massivning mos elementlari bo'linmasining qoldig'ini qaytaradi

In [ ]:
print(f"np.mod(arr_a, arr_b): {np.mod(arr_a, arr_b)}")

np.mod(arr_a, arr_b): [1 0 0 0 0]


### copysign: birinchi massiv elementlarining absolyut qiymatiga ikkinchi massiv elementlarining ishorasini qo'yadi

In [ ]:
arr_e = np.array([1.0, -2.0, 3.0, -4.0])
arr_f = np.array([-1.0, 2.0, -3.0, 4.0])
print(f"arr_e: {arr_e}")
print(f"arr_f: {arr_f}")
print(f"np.copysign(arr_e, arr_f): {np.copysign(arr_e, arr_f)}")

arr_e: [ 1. -2.  3. -4.]
arr_f: [-1.  2. -3.  4.]
np.copysign(arr_e, arr_f): [-1.  2. -3.  4.]


## Taqoslash funksiyalari (Comparison functions)

In [ ]:
arr_g = np.array([1, 2, 3, 4, 5])
arr_h = np.array([2, 2, 1, 4, 6])
print(f"arr_g: {arr_g}")
print(f"arr_h: {arr_h}")

arr_g: [1 2 3 4 5]
arr_h: [2 2 1 4 6]


### greater: birinchi massiv elementi ikkinchidan katta bo'lsa True qaytaradi

In [ ]:
print(f"np.greater(arr_g, arr_h): {np.greater(arr_g, arr_h)}")

np.greater(arr_g, arr_h): [False False  True False False]


### greater_equal: birinchi massiv elementi ikkinchidan katta yoki teng bo'lsa True qaytaradi

In [ ]:
print(f"np.greater_equal(arr_g, arr_h): {np.greater_equal(arr_g, arr_h)}")

np.greater_equal(arr_g, arr_h): [False  True  True  True False]


### less: birinchi massiv elementi ikkinchidan kichik bo'lsa True qaytaradi

In [ ]:
print(f"np.less(arr_g, arr_h): {np.less(arr_g, arr_h)}")

np.less(arr_g, arr_h): [ True False False False  True]


### less_equal: birinchi massiv elementi ikkinchidan kichik yoki teng bo'lsa True qaytaradi

In [ ]:
print(f"np.less_equal(arr_g, arr_h): {np.less_equal(arr_g, arr_h)}")

np.less_equal(arr_g, arr_h): [ True  True False  True  True]


### equal: ikkala massiv elementlari teng bo'lsa True qaytaradi

In [ ]:
print(f"np.equal(arr_g, arr_h): {np.equal(arr_g, arr_h)}")

np.equal(arr_g, arr_h): [False  True False  True False]


### not_equal: ikkala massiv elementlari teng bo'lmasa True qaytaradi

In [ ]:
print(f"np.not_equal(arr_g, arr_h): {np.not_equal(arr_g, arr_h)}")

np.not_equal(arr_g, arr_h): [ True False  True False  True]


## Mantiqiy funksiyalar (Logical functions)

In [ ]:
arr_bool1 = np.array([True, False, True, False])
arr_bool2 = np.array([True, True, False, False])
print(f"arr_bool1: {arr_bool1}")
print(f"arr_bool2: {arr_bool2}")

arr_bool1: [ True False  True False]
arr_bool2: [ True  True False False]


### logical_and: ikkala element ham True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_and(arr_bool1, arr_bool2): {np.logical_and(arr_bool1, arr_bool2)}")

np.logical_and(arr_bool1, arr_bool2): [ True False False False]


### logical_or: elementlardan hech bo'lmaganda bittasi True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_or(arr_bool1, arr_bool2): {np.logical_or(arr_bool1, arr_bool2)}")

np.logical_or(arr_bool1, arr_bool2): [ True  True  True False]


### logical_xor: elementlardan faqat bittasi True bo'lsa True qaytaradi

In [ ]:
print(f"np.logical_xor(arr_bool1, arr_bool2): {np.logical_xor(arr_bool1, arr_bool2)}")

np.logical_xor(arr_bool1, arr_bool2): [False  True  True False]
